export const portfolioConfig = {
  name: "Thiwanka Munasinghe",
  title: "Geospatial Engineer | Cartographer | Python Dev",
  description: "I am a Passionate Geospatial Engineer",
  location: "Gampaha, Sri Lanka",
  email: "thiwanka.munasinghe@hotmail.com",

  socialLinks: {
    linkedin: "https://www.linkedin.com/in/thiwankamunasinghe",
    github: "https://github.com/thiwaK",
  },

  seo: {
    ogImage: "https://thiwak.github.io/portfolio/og-image.png",
    url: "https://thiwak.github.io/portfolio",
    twitterHandle: "@thiwaK",
    keywords: [
      "thiwaK",
      "thiwak",
      "Thiwanka",
      "thiwanka",
      "Thiwanka Munasinghe",
      "thiwanka munasinghe",
      "Thiwanka Kaushal",
      "thiwanka kaushal",
      "TK Munasinghe",
      "tk munasinghe",
      "TKM",
      "Thiwanka Kaushal Munasinghe",
      "thiwanka kaushal munasinghe",
      "Munasinghe MWTK",
      "MWTK Munasinghe",
      "MW Thiwanka Kaushal Munasinghe",
      "GIS",
      "gis",
      "Geospatial",
      "geospatial",
      "Remote Sensing",
      "GIS and RS",
      "GIS & RS",
      "Geographic Information System",
      "Geographical Information System",
      "Geographic Information Science",
      "Geographical Information Science",
      "Portfolio",
      "GIS Portfolio",
      "GIS Developer",
      "Web Map",
      "GIS Dev",
      "Geospatial Solution Engineer",
      "GIS Analyst",
      "Remote Sensing Expert",
      "RS Expert",
      "Geographer",
      "Cartographer",
      "Data Analyst",
      "Data Engineer",
    ],
    authors: [
      {
        name: "Thiwanka Munasinghe",
        url: "https://github.com/thiwaK",
      },
    ],
  },

};
